### PR TITLE
Github action for automated Ubuntu builds

### LINKED ISSUE #15: libpython3.9.so.1.0: No such file or directory
**Describe the bug**
I cannot start blender on linux. Running it in the terminal give this error:
`[11800] Error loading Python lib '/tmp/_MEIQhgsTD/libpython3.9.so.1.0': dlopen: libcrypt.so.2: cannot open shared object file: No such file or directory`

**System (please complete the following information):**
 - Operation system: Linux Mint 21.2
 - Blender Launcher version:1.16

**Additional context**
I tried searching online for a fix, and it seems that this file is missing from the binary.

### PR DESCRIPTION
**Pull request by RustyNova016**
To fix #15 on Ubuntu systems, I made an automated github action that automatically build the app on version release.

For example: https://github.com/RustyNova016/Blender-Launcher-V2/releases/tag/v1.16.1

### CODE REVIEW

**Comment by zeptofine** [comment]
Could you make the naming scheme to be alike the old names? and make another task to build the debugs aswell https://github.com/DotBow/Blender-Launcher/releases/tag/v1.15.1

**Comment by zeptofine** [comment]
and looking at the action output, `pynput` isn't being collected correctly. `pynput` is used for global hotkeys. Althrough I personally don't use it, I'm sure this is used by *someone*

**Comment by RustyNova016** [comment]
I can do the debug build, but I'm not sure if it's really that useful to release.

As for the name, I think it's more appropriate to put Ubunut as it's the version for Ubuntu. Other builds could be labeled Arch or OpenSUSE, to prevent arch user to complain instead of ubuntu ones

**Comment by zeptofine** [comment]
I understand that! We'll have to rework how the updater works if we go that direction though

**Comment by zeptofine** [comment]
I think the best idea would be to find a distro-agnostic way to find the distribution name and name the builds accordingly, defaulting to the ubuntu build of course

**Comment by RustyNova016** [comment]
There's always the possibility to create a distro.py file that would contain the name of the version. 
Then during build, we change it to whatever is needed, then run pyinstaller.

Could be automated with scripts. A simple echo "..." > distro.py would do the trick.

**Comment by zeptofine** [comment]
yea maybe adding another dependency is a bit overkill. an environment variable should work just as well

**Comment by RustyNova016** [comment]
True, but would need to be ubuntu by default, or at least that the automation is able to set it itself

**Comment by zeptofine** [comment]
As I see no issues arising from these builds and they seem to work for RustyNova016 and every other Ubuntu user that has tried them have not raised an issue with these builds, I will be merging this

**Comment by freerror** [comment]
🎉

**Pull request merged**
