### PR TITLE
Toggle-library-visibility

### PR DESCRIPTION
**Pull request by zeptofine**
Like @Victor-IX mentioned in Discord, it would be good to be able to toggle the visibility of different repositories so the ones you don't care about are hidden. This implements that, and I plan on also adding this to the first-time setup screen when that is ready

### CODE REVIEW

**Comment by Victor-IX** [comment]
Did you make the icons? They look very nice! 

what do you think about having a tooltip for the description of the builds instead of a long line to make it more compact? 
image

**Comment by zeptofine** [comment]
> Did you make the icons? They look very nice!

Lol i wish i did, i used google's icons from https://fonts.google.com/icons

> what do you think about having a tooltip for the description of the builds instead of a long line to make it more compact?

Yea i can do that. do we want a <sup>?</sup> to mark a tooltip too?

**Comment by Victor-IX** [comment]
> do we want a ? to mark a tooltip too?

I don't think this is necessary

**Comment by zeptofine** [comment]
Implemented that. Should I move it to a different group? it looks a little weird in the middle of the one it's in
image

Also, I'll edit the font sizing

**Comment by zeptofine** [comment]
image

**Comment by Victor-IX** [comment]
Looks good!

**Comment by zeptofine** [comment]
As discussed on discord, disabling the library visibility now also disables the fetching

Merged the Experimental and Patch repos because in the rest of the app we don't draw a distinction between them

I added disabled colors and remade the visibility icon to look more blender-y
image

**Comment by zeptofine** [comment]
After one little bug fix i noticed, *now* it's ready. But it did emphasize the fact that the daily and experimental/patch builds don't need to be linked, they were just related because of how we fetched them and that it was faster than stable fetching. they could totally be split in the future

**Comment by Victor-IX** [comment]
image

**Three pieces of feedback I have:**

1. Is it possible to remove the empty space in the box?
>But it did emphasize the fact that the daily and experimental/patch builds don't need to be linked like you mentioned in Discord. they were just related because of how we fetched them and that it was faster than stable fetching. they could totally be split in the future
2. You are right, it would make more sense to have the *Daily* and *Experimental* scraping settings not linked, even if they are in the background. This will make the UI less confusing.
3. When clicking on the eye, scraping is disabled automatically but not clickable. I think we could make it so that clicking on scraping enables both visibility and scraping, ensuring no buttons become unclickable depending on the user's action.

**Comment by zeptofine** [comment]
> Is it possible to remove the empty space in the box?

Strange, I thought I had fixed that 🤔 must be because of GUI scaling. Ig the easiest way would be to not use a list widget, just wont look as good

> You are right, it would make more sense to have the _Daily_ and _Experimental_ scraping settings not linked, even if they are in the background. This will make the UI less confusing.

Should that be done in this PR?

> When clicking on the eye, scraping is disabled automatically but not clickable. I think we could make it so that clicking on scraping enables both visibility and scraping, ensuring no buttons become unclickable depending on the user's action.

Aight that can be done 👍🏽 

It also looks like you haven't updated the style btw

**Comment by zeptofine** [comment]
Yeah I'd like to do that separately, to keep reviewing straightforward

**Pull request merged**
