### PR TITLE
Major UI Refactor

### PR DESCRIPTION
**Pull request by zeptofine**
I might as well create this draft so people know about this
current changes I can remember:
- Most of the threads have been replaced into a worker queue handled by the main launcher
- Window headers now their own class
- Way more type hinting
- Inheritance simplifications (Specifically windows)
- Fixed a few Qt enums
- Icons are part of every BaseWindow, in a dataclass
- Partially formatted using `black`
- the progress bar is more precise (at least in the ways that we currently use it)
- Better error handling
  - This is good because it will make tracing back errors much easier, for example, ones that were previously silent, such as when blender builds are "damaged". This will help us see exactly why. 

Extracting *seems* to be a lot more stable now, but tell me if that's wrong

### CODE REVIEW

**Comment by Victor-IX** [comment]
So you moved the extraction process to the main thread?
It seems stable for me; the GUI didn't crash anymore during extraction time.
Why was it made on a separate thread? Is there a reason for doing that?

Bug:
Deleting a build is not currently working on my side.

**Comment by zeptofine** [comment]
In QT, moving processes to a separate thread makes sure it runs while the UI stays smooth. Essentially if you have code running in the main thread, the UI's event loop waits also. I didn't explain it well. basically, here, the Blender Launcher makes a few worker threads and when something needs to be done, like downloading something or renaming something, it's pushed to that worker queue instead of the widget handling its own threads.

**Comment by zeptofine** [comment]
I'll investigate that deleting issue

**Comment by zeptofine** [comment]
Just added this. Should this being in a popup be toggleable? (Sorry for bad quality, I'm using a virtual desktop currently. I'll send a better pic later)
image

**Comment by Victor-IX** [comment]
Maybe we can have a toggle to enable all debug information in the settings instead of having two different builds (I don't know what the debug build adds compared to the normal one)

**Comment by zeptofine** [comment]
The debug build adds a flag to the pyinstaller compilation to print debug information from pyinstaller. Not sure if we can do that during runtime

**Comment by zeptofine** [comment]
That being said I don't see much of a point to package that kind of information at the moment; the `-debug` flag seems to be doing fine for now

**Comment by zeptofine** [comment]
More generic close dialog
image

**Comment by zeptofine** [comment]
## More generic closing dialog
image




### Since I don't like making these huge ass changes in a single pull request, I'm just gonna mark it as ready while it's still in a stable state

**Comment by Victor-IX** [comment]
I will finish checking this code today to merge that back to dev before it becomes too big 

```py
if cpu_count is None: # why can os.cpu_count() return None
        return 4
```
When you forget to install your CPU xD

**Comment by Victor-IX** [comment]
I checked the code and did multiple tests to be sure everything was working, I had no issue on my side on Windows
Tell me when you will be ready to merge this PR

**Comment by zeptofine** [comment]
oh, yeah! Everything seems to be working for what I've tested. Just to make sure, what did you test? so I could test it on my end

**Comment by Victor-IX** [comment]
What I've tested:
- Download Build 
- Lunch Blender
- Change CPU Thred Cout (I tried to go higher than possible to make sure it was not possible)
- Multiple Download at once 
- Delete Build 

I mainly tested the main features

**Review by zeptofine — COMMENTED** [review]
Ok, I've tested these and they work perfectly! I'll merge it now

**Pull request merged**
