### PR TITLE
🐞 Fix recursive import of static method

### LINKED ISSUE #30: Crash when attempting to display file dialog window on first launch
**Describe the bug**
When running program for the first time (without Blender Launcher.ini), after clicking continue the program closes.

**To Reproduce**
1. Remove Blender Launcher.ini from the cwd of the program.
2. Run program and hit continue
3. Program quits

**Expected behavior**
File dialog opens allowing you to choose your default library location

**System (please complete the following information):**
 - Operation system: Windows 11
 - Blender Launcher version: 1.16.1
 - Log file: See relevant traceback below

**Additional context**
2023-12-17 15:51:30,489 - Windows - Blender Launcher 1.16.1
Traceback (most recent call last):
  File "L:\Blender-Launcher-V2\source\windows\main_window.py", line 165, in set_library_folder
    new_library_folder = FileDialogWindow().getExistingDirectory(
  File "L:\Blender-Launcher-V2\source\windows\file_dialog_window.py", line 14, in getExistingDirectory
    return self.getExistingDirectory(
TypeError: getExistingDirectory() takes 4 positional arguments but 5 were given

### PR DESCRIPTION
**Pull request by freerror**
- This fixes #30
- getExistingDirectory is a static method on the parent class
- Better to differentiate as a unique method of only the child class

### CODE REVIEW

**Comment by freerror** [comment]
Note: To replicate, delete `Blender Launcher.ini`

**Comment by freerror** [comment]
This was caused by changes #a1b2c3d where a single underline was removed which was differentiating the method from the parent class.

**Review by zeptofine — COMMENTED** [review]
Ah my bad, must've missed it

**Comment by zeptofine** [comment]
I do agree with a lot of the int/float typing stuff from the last pr

**Comment by freerror** [comment]
> I do agree with a lot of the int/float typing stuff from the last pr

I'm happy to do a bit of a testing on >= python 3.11 but I noticed a bug I introduced so I dropped those commits from my fork for now.

Glad I was able to help :)

**Pull request merged**
