### PR TITLE
Add new Button to open build config folder

### PR DESCRIPTION
**Pull request by Victor-IX**
Add a new button in the Right-click menu to open the Blender Config folder
#146

### CODE REVIEW

**Comment by zeptofine** [comment]
Works well for me! But I'm not sure if a silent error is the best way to go about dealing with the case of the folder not existing. Maybe we could open the blender config folder? and in the case of that not existing raising a visible error?
Also, I think this would still operate the same on bforartists. I'm not sure if bfa uses Blender's config or not

**Comment by zeptofine** [comment]
Just searched my configs, it looks like bforartists uses its own. It should look pretty similar to blender's. I found mine in `~/.config/bforartists`

**Comment by Victor-IX** [comment]
> Works well for me! But I'm not sure if a silent error is the best way to go about dealing with the case of the folder not existing. Maybe we could open the blender config folder? and in the case of that not existing raising a visible error?

This is why I opened this issue
https://github.com/Victor-IX/Blender-Launcher-V2/issues/159

> Also, I think this would still operate the same on bforartists. I'm not sure if bfa uses Blender's config or not

I completely forgot about that 😅

**Comment by zeptofine** [comment]
> https://github.com/Victor-IX/Blender-Launcher-V2/issues/159

Ah, yes, sorry I missed that last point

**Pull request merged**
