### PR TITLE
add shortcut to --use-last by holding shift while triggering a launch

### PR DESCRIPTION
**Pull request by zeptofine**
Related to #58 and #60

0:00 launching normally
0:12 Saving project
0:19 launching normally again
0:28 while holding alt, launching with the last file loaded

https://github.com/Victor-IX/Blender-Launcher-V2/assets/54873330/b8a45032-b1a2-4c33-ba0e-e43139c684a7

### CODE REVIEW

**Comment by zeptofine** [comment]
I've just remembered that some systems use alt to modify left button clicks to right click. What would be a better modifier for this other than alt?

**Comment by eisenbruch** [comment]
hmm...ctrl? shift? fn?
also just a "most recent" button would work too - maybe it can be a clock or timer icon or something like that. or maybe there is already a standard icon for "most recent"

**Comment by zeptofine** [comment]
The problem with a lot of the modifier keys is I don't want to set false positives. when people are trying to select multiple items or something they might accidentally launch the app. so I might just end up going with the button idea and add it next to the launch at the top of the context menu

**Comment by zeptofine** [comment]
I just tested it and we don't actually have a safeguard for if people shift click the launch button so that might still work
or we add a safeguard lol

**Comment by eisenbruch** [comment]
im not knowledgable enough to know the answer, but happy to test things!

**Comment by Victor-IX** [comment]
Shift can be a good key for it, but maybe we can do both a button and the shortcut

**Comment by eisenbruch** [comment]
that seems logical :)

**Comment by eisenbruch** [comment]
love how this project has been revived!!! :)
gotta think of some other great features to request.

AI integration so blender launches with 3d generated model already loaded from a prompt given through Blender Launcher before it launches lol

**Comment by eisenbruch** [comment]
> How's this? image
> 
> image

Yeah, that works!
I think it would be nice if the non shift option weren't buried in the menu, but we can see how it goes with this and if that is necessary

**Pull request merged**
