### PR TITLE
Remove unused packages

### PR DESCRIPTION
**Pull request by zeptofine**
These packages don't seem to be used by anything in the code, and nothing seems to (immediately) break for me when I remove them, so I propose removing them from the pipfile

### CODE REVIEW

**Comment by zeptofine** [comment]
Draft because, once again, I am unsure if anything changes on the Windows side. I can check myself in a couple hours

**Comment by Victor-IX** [comment]
I will check on my side to see if everything works on Windows

**Comment by Victor-IX** [comment]
I checked quickly on Windows and didn't get any issue

**Comment by zeptofine** [comment]
Pywin32 seems to include the `win32com` module so that'll have to be re-added. This could be closed if the pyproject.toml version passes, we could just switch to that

**Comment by zeptofine** [comment]
Closed as the pyproject route was done

**Pull request closed without merging**
