### PR TITLE
Add checkboxes to scrape only stable or automated builds

### PR DESCRIPTION
**Pull request by zeptofine**
For some of us, it is a waste of time / bandwidth to scrape the stable builds because they usually use the daily/experimental builds, and on the flipside, some never intend to use the daily/experimental builds. These two options allow someone to just skip the different methods.

### CODE REVIEW

**Comment by Victor-IX** [comment]
After disabling automatic build scraping for Daly you can't manually scrap them with the Check button

**Comment by zeptofine** [comment]
I can set that as fixed, but maybe we could make that a choice with shift-clicking like on the builds?

**Comment by Victor-IX** [comment]
Not sure what you mean by shift-clicking. It will gather the build if automatic scraping is disabled if you shift-click the Check button?

**Comment by zeptofine** [comment]
I mean if you hold shift and press the button, it tries to gather both stable and automated builds no matter what your settings are

**Comment by Victor-IX** [comment]
oh ok, yep that's a good idea

**Pull request merged**
