### PR TITLE
Add architecture displays to builds

### PR DESCRIPTION
**Pull request by zeptofine**
This adds an architecture notification to the branch string in certain builds, in the same style that MacOS builds are displayed.

image

- [x] Daily builds
- [ ] Builds in library

Would we want to add an architecture value to build infos?

### CODE REVIEW

**Comment by Victor-IX** [comment]
For some reason, the x64 build has the amd64 Architecture in the JSON file and the .zip file name

image

```JSON
{
        "url": "https://builder.blender.org/download/daily/blender-4.2.0-alpha+main.3be6dbb02a06-windows.amd64-release.zip",
        "app": "Blender",
        "version": "4.2.0",
        "risk_id": "alpha",
        "branch": "main",
        "patch": null,
        "hash": "3be6dbb02a06",
        "platform": "windows",
        "architecture": "amd64",
        "bitness": 64,
        "file_mtime": 1714871923,
        "file_name": "blender-4.2.0-alpha+main.3be6dbb02a06-windows.amd64-release.zip",
        "file_size": 439875335,
        "file_extension": "zip",
        "release_cycle": "alpha"
    },
```

**Comment by Victor-IX** [comment]
I will do a quick bug report to the Blender Foundation

**Comment by zeptofine** [comment]
Blender doesn't ship x64 builds, they just ship amd64 builds but they still work on both intel and amd chips, so i think its fine. But i do find it strange that they are mislabeling them

**Comment by Victor-IX** [comment]
Ok, so what's the difference between the x86_64 build and the Amd64?

**Comment by Victor-IX** [comment]
From what I read x86_64 and Amd64 are the same thing...
`x86-64 (also called x86_64, x64, or amd64) is the 64-bit CPU architecture that is used in Intel and AMD processors`

**Comment by Victor-IX** [comment]
Nevermind I just don't know who to read😅, I read and64 instead of arm64, so I thought all the builds had the same Architecture label xD

**Comment by Victor-IX** [comment]
For the build info question, I don't see why we would need this information saved. 
Also, I don't think having this info in the build library is relevant, as the user will already have downloaded the build that is working on their system.
Maybe we can improve this to only show the builds with the currently used Architecture

**Pull request merged**
