### PR TITLE
add linux installation extras

### PR DESCRIPTION
**Pull request by sakarimov**
i made an AUR repo for archlinux users, so they can easily install it immediately from the repo, basically it will install the binary to the ```$PATH``` and then adding the .desktop file to ```/usr/share/applications/```

### CODE REVIEW

**Comment by Victor-IX** [comment]
I'm unfamiliar with AUR, is it downloading the repo content or the latest Linux release?
Also if it's using the latest release, is it pulling it from Git or do you have to upload it manually on the AUR platform?

**Comment by sakarimov** [comment]
i made two kind of it [blender-launcher-git](https://aur.archlinux.org/packages/blender-launcher-git) and [blender-launcher-bin](https://aur.archlinux.org/packages/blender-launcher-git), the first will download from the repo and build on every installation, and the second will download from linux release and install it to the ```$PATH```, it would be convenient if you also include the ```.desktop``` file and ```bl.png``` to the linux release, so the desktop can have proper icon on it

**Comment by zeptofine** [comment]
Alright, you've uploaded the package so it's already been done

- Are you available to help with issues related to the AUR package if some come up? 
- Try to make it relative to `main` (I would have, but it seems your pr is based on 1.15.0 stable)
- Please make a mention in the docs that the AUR package is not maintained by us

**Comment by sakarimov** [comment]
it's uploaded, but on the package that is based on release it's still lack proper ```.desktop``` file and and icon, therefore i asked to include that on the zip file, and about those points:

- i inshaAllah will be available
- okay, will check
- okay, will do

**Comment by sakarimov** [comment]
All are done, i made new PR #101

**Comment by zeptofine** [comment]
Closed in favor of #101

**Pull request closed without merging**
