### PR TITLE
Adding a Installed Button in the Download Tab for already installed build

### PR DESCRIPTION
**Pull request by Victor-IX**
For visibility,

_To work on this feature, I branched from UI refactor to prevent conflicts, so I will merge this PR when your refactor is done._

I added a new button for an already installed build in the Download tab; the color is not working. I need to figure out how this system works 😄

image

### CODE REVIEW

**Comment by eisenbruch** [comment]
I like this feature. 

Does this mean that if I install a build and then delete it from my drive, I will be able to redownload it again in the future?

I think in current build if you delete a version it seems to be gone forever, with no way to download it again.

**Comment by Victor-IX** [comment]
Yes, you will be able to download it again. I think there is a bug in the current build, when you delete a build, it doesn't appear directly in the download tab. To have teh build available again, you need to restart the Blender launcher.
I will try to fix this bug at the same time

**Comment by eisenbruch** [comment]
hmm, i think even when i restart blender launcher the old builds dont show
back up. if they did id have a bunch of old builds of the same version
number there but i dont.

thanks!

**Comment by zeptofine** [comment]
Good idea! Pretty sure you need to run build_style.py in order for any css changes to apply.

I think I've found a bug: you can still double click builds that are already installed and it will still trigger a download

**Comment by Victor-IX** [comment]
> I think I've found a bug: you can still double click builds that are already installed and it will still trigger a download

Yep, I've not integrated the code to prevent that

**Pull request merged**
